projeto/urls.py
from os import stat
from turtle import st

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include('recipes.urls')),
    path('admin/', admin.site.urls),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path

from . import views

app_name = 'recipes'

urlpatterns = [
    path("", views.home, name="home"),
    path("recipes/category/<int:category_id>/",
         views.category, name="category"),
    path("recipes/<int:id>/", views.recipes, name="detail"),

]

recipes/models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name


class Recipe(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField()
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=65)
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(upload_to='recipes/covers/%Y/%m/%d/')
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, blank=True, default=None)
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.title

recipes/views.py
from django.shortcuts import get_list_or_404, get_object_or_404, render
from utils.recipes.factory import make_recipe

from .models import Recipe


def home(request):
    recipes = Recipe.objects.filter(is_published=True).order_by('-id')

    return render(request, 'recipes/home.html', context={
        'recipes': recipes
    })


def category(request, category_id):
    # recipes = Recipe.objects.filter(
    #     category__id=category_id, is_published=True).order_by('-id')

    recipes = get_list_or_404(
        Recipe.objects.filter(
            category__id=category_id, is_published=True).order_by('-id'))

    return render(request, 'recipes/category.html', context={
        'recipes': recipes,
        'title': f'{recipes[0].category.name} - Category'
    })


def recipes(request, id):
    recipe = get_object_or_404(Recipe, pk=id, is_published=True)

    return render(request, 'recipes/recipe-view.html', context={
        'recipe': recipe,
        'is_detail_page': True
    })

recipes/templates/partials/footer.html
<footer class="main-footer">
    <div class="developer">
      <a href="https://www.jcesteves.com.br/" target="_blank" rel="noreferrer noopener">By Julio C Esteves</a>
    </div>
  
    <div class="powered">
      <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">Powered by Django</a>
    </div>
  </footer> 

recipes/templates/partials/head.html
{% load static %}
   
   <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/fontawesome.min.css"
        integrity="sha512-8Vtie9oRR62i7vkmVUISvuwOeipGv8Jd+Sur/ORKDD5JiLgTGeBSkI3ISOhc730VGvA5VVQPwKIKlmi+zMZ71w=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/brands.min.css"
        integrity="sha512-bSncow0ApIhONbz+pNI52n0trz5fMWbgteHsonaPk42JbunIeM9ee+zTYAUP1eLPky5wP0XZ7MSLAPxKkwnlzw=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/solid.min.css"
        integrity="sha512-6/gTF62BJ06BajySRzTm7i8N2ZZ6StspU9uVWDdoBiuuNu5rs1a8VwiJ7skCz2BcvhpipLKfFerXkuzs+npeKA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Montserrat:wght@900&family=Open+Sans:ital,wght@0,400;0,700;1,400&family=Roboto:ital,wght@1,900&display=swap"
        rel="stylesheet">
    
    <link rel="stylesheet" href={% static 'recipes/css/styles.css' %}>
    

recipes/templates/partials/header.html
<header class="main-header-container">
    <div class="main-header container">
        <h1>
            <a class="main-logo" href="{% url 'recipes:home' %}">
                <i class="fa fa-book main-logo-icon"></i></i>
                <span class="main-logo-text">Recipes</span>
            </a>
        </h1>
    </div>
</header>

recipes/templates/partials/recipe.html
<div class="recipe recipe-list-item">
    <div class="recipe-cover">
        <a href="{% url 'recipes:detail' recipe.id %}">
            <img src="{{recipe.cover.url}}" alt="Temporário">
        </a>
    </div>
    <div class="recipe-title-container">
        <a href="{% url 'recipes:detail' recipe.id %}">
            <h2 class="recipe-title">{{recipe.title}}</h2>
        </a>
    </div>
    <div class="recipe-author">

        {% if recipe.author is not None %}
            <span class="recipe-author-item">
                <i class="fas fa-user"></i>
                {% if recipe.author.first_name %}
                    {{recipe.author.first_name}} {{recipe.author.last_name}}
                {% else %}
                    {{recipe.author.username}}
                {% endif %}
            </span>
        {% endif %}        

        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{recipe.created_at | date:"d/m/Y"}} às {{recipe.created_at | date:"H:i"}}
        </span>

        {% if recipe.category is not None %}
            <span class="recipe-author-item">
                <a href="{% url 'recipes:category' recipe.id %}">
                    <i class="fas fa-layer-group"></i>
                    <span>{{recipe.category.name}}</span>
                </a>
            </span>
        {% endif %}

    </div>
    <div class="recipe-content">
        <p>{{recipe.preparation_steps}}</p>
    </div>
    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i>Preparo</h3>
            <div class="recipe-meta-text">
                {{recipe.preparation_time}} {{recipe.preparation_time_unit}}
            </div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i>Porções</h3>
            <div class="recipe-meta-text">
                {{recipe.servings}} {{recipe.servings_unit}}
            </div>
        </div>
    </div>

    {% if is_detail_page is not True %}
    <footer class="recipe-footer">
        <a class="recipe-read-more button button-dark button-full-width" href="{% url 'recipes:detail' recipe.id %}">
            <i class="fas fa-eye"></i>
            <span>ver mais...</span>
        </a>
    </footer>
    {% endif %}

    {% if is_detail_page is True %}
    <div class="preparation-steps">
        {% if recipe.preparation_steps_is_html is True %}
            {{recipe.preparation_steps | safe}}
        {% else %}
            {{recipe.preparation_steps | linebreaksbr}}
        {% endif %}
    </div>
    {% endif %}
</div>

recipes/templates/partials/search.html
<div class="search-container">
    <div class="container">
        <form action="" class="search-form">
            <input type="search" name="search" id="search-input" class="search-input">
            <button type="submit" class="search-button"><i class="fa fa-search"></i></button>
        </form>
    </div>
</div>

recipes/templates/recipes/category.html
{% extends 'global/base.html' %}

{% block title %} {{title}} {% endblock title %}

{% block main-content %}
<div class="main-content main-content-list container">
    {% for recipe in recipes %}
        {% include 'partials/recipe.html' %}
    {% endfor %}
</div>
{% endblock main-content %}

recipes/templates/recipes/home.html
{% extends 'global/base.html' %}

{% block main-content %}
<div class="main-content main-content-list container">
    {% for recipe in recipes %}
        {% include 'partials/recipe.html' %}
    {% empty %}
        <div class="center">
            <h1>Não existem receitas cadastradas ou ainda não foram publicadas. 😥</h1>
        </div>
    {% endfor %}    
</div>
{% endblock main-content %}

recipes/templates/recipes/recipe-view.html
{% extends 'global/base.html' %}

<title>{% block title %}Recipes-View{% endblock title %}</title>

{% block main-content %}
<div class="main-content main-content-detail container">
    {% include 'partials/recipe.html' %}
</div>
{% endblock main-content %}